// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdkfSEXOd5qM7ElWu97zy6cLkpP12IN80',
    appId: '1:603806690873:web:2afd4705dffab82c79a7e8',
    messagingSenderId: '603806690873',
    projectId: 'doctor-car-2025',
    authDomain: 'doctor-car-2025.firebaseapp.com',
    storageBucket: 'doctor-car-2025.firebasestorage.app',
    measurementId: 'G-XKGVNCT1TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNc3JcOsFSpjskJEnlVUGCJ-nQHjKu-fY',
    appId: '1:603806690873:android:a48d4838cfc6bc0679a7e8',
    messagingSenderId: '603806690873',
    projectId: 'doctor-car-2025',
    storageBucket: 'doctor-car-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ6rh19Gq1z7pHFBFFtYrImU56sAKIB6U',
    appId: '1:603806690873:ios:fedcaf9e8fa901be79a7e8',
    messagingSenderId: '603806690873',
    projectId: 'doctor-car-2025',
    storageBucket: 'doctor-car-2025.firebasestorage.app',
    iosBundleId: 'com.example.car3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ6rh19Gq1z7pHFBFFtYrImU56sAKIB6U',
    appId: '1:603806690873:ios:fedcaf9e8fa901be79a7e8',
    messagingSenderId: '603806690873',
    projectId: 'doctor-car-2025',
    storageBucket: 'doctor-car-2025.firebasestorage.app',
    iosBundleId: 'com.example.car3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdkfSEXOd5qM7ElWu97zy6cLkpP12IN80',
    appId: '1:603806690873:web:bb21634ea6d793ba79a7e8',
    messagingSenderId: '603806690873',
    projectId: 'doctor-car-2025',
    authDomain: 'doctor-car-2025.firebaseapp.com',
    storageBucket: 'doctor-car-2025.firebasestorage.app',
    measurementId: 'G-NM4RVCXNKJ',
  );
}
